from __future__ import annotations

from typing import Protocol

from .models import BrokerOrderCommand, BrokerOrderSnapshot, BrokerPositionSnapshot


class BrokerClient(Protocol):
    def get_order_by_client_order_id(self, client_order_id: str) -> BrokerOrderSnapshot: ...
    def submit_order(self, command: BrokerOrderCommand) -> BrokerOrderSnapshot: ...
    def cancel_order(self, broker_order_id: str) -> None: ...
    def get_order(self, broker_order_id: str) -> BrokerOrderSnapshot: ...
    def get_position(self, symbol: str) -> BrokerPositionSnapshot | None: ...
