from __future__ import annotations

from enum import StrEnum


class RiskProfileName(StrEnum):
    PAPER_V1 = "paper_v1"
    LIVE_PILOT_V1 = "live_pilot_v1"


class RiskDecisionStatus(StrEnum):
    APPROVED = "approved"
    REJECTED = "rejected"


class BindingCap(StrEnum):
    TRADE_RISK = "TRADE_RISK"
    OPEN_RISK = "OPEN_RISK"
    DAILY_LOSS = "DAILY_LOSS"
    BUYING_POWER = "BUYING_POWER"
    POSITION_NOTIONAL = "POSITION_NOTIONAL"
    GROSS_EXPOSURE = "GROSS_EXPOSURE"
    ADV_LIQUIDITY = "ADV_LIQUIDITY"
    PREMARKET_LIQUIDITY = "PREMARKET_LIQUIDITY"


class RiskRejectionCode(StrEnum):
    ACCOUNT_NOT_ACTIVE = "ACCOUNT_NOT_ACTIVE"
    ACCOUNT_BLOCKED = "ACCOUNT_BLOCKED"
    TRADING_BLOCKED = "TRADING_BLOCKED"
    TRADE_SUSPENDED_BY_USER = "TRADE_SUSPENDED_BY_USER"
    ACCOUNT_SNAPSHOT_STALE = "ACCOUNT_SNAPSHOT_STALE"
    INVALID_ACCOUNT_VALUE = "INVALID_ACCOUNT_VALUE"
    PENDING_TRANSFER_OUT = "PENDING_TRANSFER_OUT"
    ACCOUNT_STATE_UNRECONCILED = "ACCOUNT_STATE_UNRECONCILED"
    STREAM_HEALTH_FAILURE = "STREAM_HEALTH_FAILURE"
    DATABASE_HEALTH_FAILURE = "DATABASE_HEALTH_FAILURE"
    KILL_SWITCH_ACTIVE = "KILL_SWITCH_ACTIVE"
    MARKET_NOT_NORMAL = "MARKET_NOT_NORMAL"
    SYMBOL_HALTED = "SYMBOL_HALTED"
    EXECUTION_CUTOFF_EXCEEDED = "EXECUTION_CUTOFF_EXCEEDED"
    QUOTE_SNAPSHOT_STALE = "QUOTE_SNAPSHOT_STALE"
    LAST_TRADE_STALE = "LAST_TRADE_STALE"
    INVALID_QUOTE = "INVALID_QUOTE"
    REGULAR_SESSION_NBBO_NOT_CONFIRMED = "REGULAR_SESSION_NBBO_NOT_CONFIRMED"
    SPREAD_TOO_WIDE = "SPREAD_TOO_WIDE"
    ENTRY_PRICE_DRIFT_TOO_LARGE = "ENTRY_PRICE_DRIFT_TOO_LARGE"
    ENTRY_LIMIT_NOT_MARKETABLE = "ENTRY_LIMIT_NOT_MARKETABLE"
    INVALID_PRICE_GEOMETRY = "INVALID_PRICE_GEOMETRY"
    PREMARKET_LOW_BROKEN = "PREMARKET_LOW_BROKEN"
    STOP_ABOVE_PREMARKET_LOW = "STOP_ABOVE_PREMARKET_LOW"
    INVALID_LIQUIDITY_INPUT = "INVALID_LIQUIDITY_INPUT"
    SOFT_DAILY_LOSS_LIMIT = "SOFT_DAILY_LOSS_LIMIT"
    HARD_DAILY_LOSS_LIMIT = "HARD_DAILY_LOSS_LIMIT"
    SESSION_PNL_RECONCILIATION_FAILURE = "SESSION_PNL_RECONCILIATION_FAILURE"
    MAX_CONSECUTIVE_LOSSES = "MAX_CONSECUTIVE_LOSSES"
    MAX_NEW_ENTRIES_PER_DAY = "MAX_NEW_ENTRIES_PER_DAY"
    DUPLICATE_TICKER_DAY = "DUPLICATE_TICKER_DAY"
    MAX_CONCURRENT_POSITIONS = "MAX_CONCURRENT_POSITIONS"
    NO_BUYING_POWER_CAPACITY = "NO_BUYING_POWER_CAPACITY"
    NO_OPEN_RISK_CAPACITY = "NO_OPEN_RISK_CAPACITY"
    NO_DAILY_LOSS_CAPACITY = "NO_DAILY_LOSS_CAPACITY"
    NO_GROSS_EXPOSURE_CAPACITY = "NO_GROSS_EXPOSURE_CAPACITY"
    FINAL_QUANTITY_BELOW_MINIMUM = "FINAL_QUANTITY_BELOW_MINIMUM"
    INVALID_POLICY_CONFIGURATION = "INVALID_POLICY_CONFIGURATION"


class ReservationStatus(StrEnum):
    RESERVED = "reserved"
    SUBMITTED = "submitted"
    PARTIALLY_FILLED = "partially_filled"
    FILLED = "filled"
    RELEASED = "released"
    EXPIRED = "expired"
    RECONCILIATION_REQUIRED = "reconciliation_required"
